apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.example.io
spec:
  group: samplecrd.example.io
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        cidr:
          type: string
        gateway:
          type: string
  names:
    kind: Network
    plural: networks
  scope: Namespaced
