apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.example.io
spec:
  group: samplecrd.example.io
  version: v1
  names:
    kind: Network
    plural: networks
  scope: Namespaced
